accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts.views import Aboutpageview
from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^about/',Aboutpageview.as_view(),name='about'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('predict_risk.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict_risk/urls.py
from django.conf.urls import url
from . import views
app_name='predict'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf.urls import url
from django.shortcuts import resolve_url


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to='profile_pics', default="1.jpg")

    def __str__(self):
        return self.user.username

# Create your models here.

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter username'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter password'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm password'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm password does not match"
            )


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {'username': forms.TextInput(attrs={'readonly': 'True'})}

accounts/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm, UpdateProfileForm
from django.views.generic import DetailView,UpdateView,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, User
from django.shortcuts import get_object_or_404
# Create your views here.

@login_required
def user_logout(request):
    #del request.session['user_id']
    request.session.flush()
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

class Aboutpageview(TemplateView):
    template_name='accounts/about.html';


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            return HttpResponseRedirect(reverse('user_login'))

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = user.profile.pk

                return HttpResponseRedirect(reverse('predict:predict', kwargs={'pk': user.profile.pk}))
            else:
                return HttpResponse("Account not active")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'accounts/login.html', {})

class ProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = UserProfileInfo
    template_name = 'accounts/profileview.html'

    def get_context_data(self, **kwargs):
        if self.request.session.has_key('user_id'):
            u_id = self.request.session['user_id']
            context = super(ProfileDetailView, self).get_context_data(**kwargs)
            context['user_id'] = u_id

        return context

accounts/templates/accounts/profileview.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

    
			<!--CSS-->
					

            <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet" media="all">
            <!-- Bootstrap bootstrap-touch-slider Slider Main Style Sheet -->

            <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
            <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
            <link href="{% static 'css/login.css' %}" rel="stylesheet" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

            <!-- Site CSS -->
			<link rel="stylesheet" href="{% static 'css/my_style.css' %}">
			<link rel="stylesheet" href="{% static 'css/boxicons/css/boxicons.min.css' %}">


            <!-- Responsive CSS -->
            <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
            <link rel="stylesheet" href="{% static 'css/landing_page.css' %}">
            <link rel="stylesheet" href="{% static 'css/custom_predict.css' %}">

    <meta charset="UTF-8">
    <title></title>

</head>


<body id="profile" data-spy="scroll" data-target="#navbar-wd" data-offset="98" class="profile-page sidebar-collapse">

	<!-- Start top bar -->
	<div class="main-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="left-top">
						<a class="new-btn-d br-2" href="#"><span>Check Heart Disease</span></a>
						<div class="mail-b"><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i> Zunaidk17@gmail.com</a></div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="wel-nots">
						<p>Welcome to Our Health Lab!</p>
					</div>
					<div class="right-top">
						<ul>
							<li><a href="https://www.facebook.com/Smart-Heart-Disease-System-104554694850034"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End top bar -->







    <!-- Start header -->
	<header  class="top-header">
		<nav  class="navbar header-nav navbar-expand-lg">
            <div   class="container">
				<a class="navbar-brand" href="#"><img src="{% static 'images/logo.png' %}" alt="image"></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
					<span></span>
					<span></span>
					<span></span>
				</button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul  class="navbar-nav">
						<li><a class="nav-link " href="#profile">Profile</a></li>
						<li><a class="nav-link" href="{% url 'predict:predict' pk=user_id %}">Predict</a></li>
                        <li><a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>
	</header>



    <div class="wrapper">
        <div style="background-image: linear-gradient(to right, #48c6ef , #6f86d6 );"    class="page-header page-header-small" filter-color="orange" style="max-height: 100px;">
            <div  class="container">
                <div  class=" content-center">
        
                    <div  class="photo-container">
                
                        <img width="100%" height="auto"  src="{{userprofileinfo.profile_pic.url}}" />
                    </div>
                    <h3 style="color: cornsilk;" class="title">{{ userprofileinfo.user.username }}</h3>
                    <p class="h5">{{ userprofileinfo.user.email }}</p>


                    </div>
                </div>
            </div>
        </div>

        
    <div class="section">
            <div class="container">
                <div class="button-container">

                        <i class="fa fa-github"></i>
                    </a>

                </div>
            </div>
    </div>
    <div style="margin-top: 120px;" class="container">
    <div style="background-image: linear-gradient(to right,#0c5872 , #5071e6);" class="card-header  btn-round text-white">Predictions</div>
        <hr>


        {% for pred in userprofileinfo.predict.all  %}
            <br>

             <div class="card card-login" style="width: 100%">
                    <div style="background-image: linear-gradient(to right,#00c6ff , #0072ff);" class="card-header text-white" style="height: 50px;"> Prediction : {{ pred.num|safe}}
                    </div>
                    <div class="container">
                        <br>
                        <p>Age: {{pred.age}}</p>
                        <p>Sex: {{pred.sex}}</p>
                    </div>
                    <div class="card-footer bg-light" >Predicted on {{ pred.predicted_on }}</div>

            </div>
            <br>
        {% endfor %}


    </div>


    <br><br>
    
	<!-- ======= Footer ======= -->
	<footer id="footer">    
        <div class="container footer-bottom clearfix">
          <div class="copyright">
            &copy; Copyright <strong><span>Mohd zunaid</span></strong>. All Rights Reserved
          </div>
          <div class="credits">
              <div class="col-lg-12">
                  <p class="footer-company-name">All Rights Reserved. &copy; 2020 <a href="#">Health Lab</a> Design By : Mohd Zunaid & Sanjana</a></p>
              </div>
          </div>
        </div>
      </footer><!-- End Footer -->
</body>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- ALL PLUGINS -->
<script src="{% static 'js/form-validator.min.js' %}"></script>
<script src="{% static 'js/contact-form-script.js' % }"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/TweenMax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/custom.js'%}"></script>
<script src="{% static 'js/owl-carousel.min.js'%}"></script>

<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap_ui_kit.js' %}" type="text/javascript"></script>
</html>